[supervisord]
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/

[program:file_management_service]
command=../file_management_env ../microservices/file_management_service.py
autostart=true
autorestart=true
stderr_logfile=/var/log/file_management.err.log
stdout_logfile=/var/log/file_management.out.log

[program:domain_prediction_service]
command=../domain_prediction_env ../microservices/domain_prediction_service.py
autostart=true
autorestart=true
stderr_logfile=/var/log/domain_prediction.err.log
stdout_logfile=/var/log/domain_prediction.out.log

[program:task_prediction_service]
command=../task_prediction_env ../microservices/task_prediction_service.py
autostart=true
autorestart=true
stderr_logfile=/var/log/task_prediction.err.log
stdout_logfile=/var/log/task_prediction.out.log

[program:report_generation_service]
command= ../report_generation_env ../microservices/report_generation_service.py
autostart=true
autorestart=true
stderr_logfile=/var/log/report_generation.err.log
stdout_logfile=/var/log/report_generation.out.log
