name: SonarCloud Scan
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloudScan1:
    name: SonarCloudScan1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Create virtual environments if not exist
        run: |
          python -m venv server/envs/api_gateway_env
          python -m venv server/envs/test_env

      - name: Install dependencies in virtual environments
        run: |
          source server/envs/api_gateway_env/bin/activate && pip install -r server/envs/requirements.txt
          deactivate
          source server/envs/test_env/bin/activate && pip install pytest
          deactivate

      - name: Start API Gateway
        run: |
          source server/envs/api_gateway_env/bin/activate
          nohup python server/api_gateway/api_gateway.py &
          sleep 2

      - name: Run Pytest
        env:
          DISPLAY: :99
        run: |
          source server/envs/test_env/bin/activate
          pytest system_test/tests --maxfail=1 --disable-warnings -q

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SERVER }}
        with:
          projectBaseDir: refair-server/

  sonarcloudScan2:
    name: SonarCloudScan2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./client/web_app

      - name: Test and coverage
        run: npm run coverage
        working-directory: ./client/web_app

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
        with:
          projectBaseDir: client/web_app/